[package]
name = "releasy-core"
version = "0.0.0"
edition = "2021"

[dependencies]
reqwest = "0.11.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.48"
