[package]
name = "releasy-handler"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.2", features = ["derive"] }
releasy-graph = { path = "../releasy-graph/" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
